language: go

go:
- 1.12.x
- 1.13.x
- 1.14.x
- 1.15.x
- tip

os:
- linux
- osx
- windows

before_install:
- go get github.com/mattn/goveralls

script:
- $GOPATH/bin/goveralls -service=travis-ci

matrix:
    allow_failures:
     - os: windows

