language: go

go:
- 1.12.x
- master

os:
- linux
- osx
- windows

env: GO111MODULE=on GOFLAGS='-mod vendor'

before_install:
- go get github.com/mattn/goveralls

script:
- $GOPATH/bin/goveralls -service=travis-ci

