language: go

go:
- 1.12
- master

os:
- linux
- osx
- windows

env: GO111MODULE=on GOFLAGS='-mod vendor'

before_script:
- go install github.com/mattn/goveralls

script:
- goveralls -service=travis-ci

