name: Go
on:
  push:
    branches:
      - "main"
      - "gen-docs"
  pull_request:
    branches:
      - "main"
jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        version: [ '1.12', 'stable', 'oldstable', ]

    runs-on: ${{ matrix.os }}

    name: Build
      #runs-on: ubuntu-latest
    steps:

    - name: Set up Go ${{ matrix.version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}

      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .
      
    - name: Test
      run: go test -v .
