name: Go
on:
  push:
    branches:
      - "main"
      - "gen-docs"
  pull_request:
    branches:
      - "main"
jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        version: [ '1.12', 'stable', 'oldstable', ]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Set up Go ${{ matrix.version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}

    - name: Check out
      uses: actions/checkout@v4

    - name: Build
      run: go build -v .
      
    - name: Test
      run: go test -v .
